### ISSUE TITLE
Question about ExportedDefaultBinding ::= IdentifierName

### ISSUE THREAD

**Issue by spket** [leebyron/ecmascript-more-export-from#6]
Should following statment both valid? same for: class, var, const, let, do I have to look ahead to tell which path to choose?

``` javascript
export function from "a"
export function from () {}
```

**Comment by caridy** [comment]
no, there is not need to look ahead because `function` means function declaration with or without a name, in which case the first one will fail, while the second one will pass.

IIRC the implementation in esprima does a lookahead but just to determine whether the function has a name or not.

The same applies to all other variants.

**Comment by spket** [comment]
Then maybe it should made clear in Spec, for example like:

export default [lookahead ! {function, class, from}] AssignmentExpression[In] ;

**Comment by caridy** [comment]
no, the spec is clear on that regards. the fact that we do so in esprima is just an implementation detail to reuse the function declaration parser, but in the spec a function without a name is very well defined. You can find a lot of discussion around that topic in esdiscuss and espree repo.

**Comment by spket** [comment]
It's not about function declaration...

``` javascript
export IdentifierName from module
```

is conflict with

``` javascript
export Declaration
```

when IdentifierName is function/class/let/const, and conflict with

``` javascript
export VariableStatement
```

when IdentifierName is var

and why use esprima as example? I just check it's source code, it does not even support additional export from statements in ES 7?

**Comment by leebyron** [comment]
Look ahead restrictions in grammars are necessary to remove ambiguity, but there is no ambiguity here. Your first example is unambiguously an export-from and your second example is unambiguously an exported function. 

Parser implementations need to look ahead to know what paths to take. In an LR(1) grammar, rules are designed to only require a single token look ahead in order to know which path to take, which is maybe what you were referring to here. However JavaScript is not an LR(1) grammar as there are already other cases in the language where a further look ahead is required. In this case, after lexing "function" and two paths are possible, a look ahead of two tokens is necessary.
